### PR TITLE
company name updated

### PR DESCRIPTION
**Pull request by Awa26**
modified cydeo to our project name, which is our company name "TryCloud".

### CODE REVIEW

**Review by balfaro2 — COMMENTED** [review]
everything looks good

**Review by AshleyKucuk — APPROVED** [review]
approved

**Comment by zubex84** [comment]
Perfect!

**Review by balfaro2 — APPROVED** [review]
looks good

**Review by alpolon — APPROVED** [review]

**Review by zubex84 — APPROVED** [review]

**Pull request merged**
